# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(715, 582)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_9 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.treeWidget = QtGui.QTreeWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.treeWidget.setAutoFillBackground(False)
        self.treeWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setAnimated(True)
        self.treeWidget.setHeaderHidden(False)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.stackedWidget = QtGui.QStackedWidget(self.splitter)
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.pageModel = QtGui.QWidget()
        self.pageModel.setObjectName(_fromUtf8("pageModel"))
        self.gridLayout_5 = QtGui.QGridLayout(self.pageModel)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.pageModel)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEditModelName = QtGui.QLineEdit(self.pageModel)
        self.lineEditModelName.setObjectName(_fromUtf8("lineEditModelName"))
        self.horizontalLayout_2.addWidget(self.lineEditModelName)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tabWidget = QtGui.QTabWidget(self.pageModel)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEditTimeUnits = QtGui.QLineEdit(self.tab)
        self.lineEditTimeUnits.setObjectName(_fromUtf8("lineEditTimeUnits"))
        self.gridLayout_2.addWidget(self.lineEditTimeUnits, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 2, 1, 1)
        self.lineEditVolumeUnits = QtGui.QLineEdit(self.tab)
        self.lineEditVolumeUnits.setObjectName(_fromUtf8("lineEditVolumeUnits"))
        self.gridLayout_2.addWidget(self.lineEditVolumeUnits, 0, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.lineEditQuantityUnits = QtGui.QLineEdit(self.tab)
        self.lineEditQuantityUnits.setObjectName(_fromUtf8("lineEditQuantityUnits"))
        self.gridLayout_2.addWidget(self.lineEditQuantityUnits, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.lineEdit_5 = QtGui.QLineEdit(self.tab)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.gridLayout_2.addWidget(self.lineEdit_5, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 2, 2, 1, 1)
        self.lineEdit_6 = QtGui.QLineEdit(self.tab)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.gridLayout_2.addWidget(self.lineEdit_6, 2, 3, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.line_3 = QtGui.QFrame(self.tab)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout_8.addWidget(self.line_3)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_3.addWidget(self.label_24, 2, 0, 1, 1)
        self.modelErrorLog = QtGui.QPlainTextEdit(self.tab)
        self.modelErrorLog.setReadOnly(True)
        self.modelErrorLog.setObjectName(_fromUtf8("modelErrorLog"))
        self.gridLayout_3.addWidget(self.modelErrorLog, 3, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.pushButtonModelCommit = QtGui.QPushButton(self.tab)
        self.pushButtonModelCommit.setObjectName(_fromUtf8("pushButtonModelCommit"))
        self.gridLayout_4.addWidget(self.pushButtonModelCommit, 0, 0, 1, 1)
        self.pushButtonModelRevert = QtGui.QPushButton(self.tab)
        self.pushButtonModelRevert.setObjectName(_fromUtf8("pushButtonModelRevert"))
        self.gridLayout_4.addWidget(self.pushButtonModelRevert, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 4, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_15 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.plainTextEdit = QtGui.QPlainTextEdit(self.tab_2)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.gridLayout_15.addWidget(self.plainTextEdit, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.gridLayout_5.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageModel)
        self.pageCompartments = QtGui.QWidget()
        self.pageCompartments.setObjectName(_fromUtf8("pageCompartments"))
        self.gridLayout_7 = QtGui.QGridLayout(self.pageCompartments)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_7 = QtGui.QLabel(self.pageCompartments)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_6.addWidget(self.label_7, 0, 0, 1, 1)
        self.lineSearchCompartments = QtGui.QLineEdit(self.pageCompartments)
        self.lineSearchCompartments.setObjectName(_fromUtf8("lineSearchCompartments"))
        self.gridLayout_6.addWidget(self.lineSearchCompartments, 0, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.splitter_4 = QtGui.QSplitter(self.pageCompartments)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.tableCompartments = QtGui.QTableWidget(self.splitter_4)
        self.tableCompartments.setAlternatingRowColors(True)
        self.tableCompartments.setCornerButtonEnabled(True)
        self.tableCompartments.setProperty("RowNumber", 1)
        self.tableCompartments.setObjectName(_fromUtf8("tableCompartments"))
        self.tableCompartments.setColumnCount(5)
        self.tableCompartments.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableCompartments.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableCompartments.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableCompartments.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableCompartments.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableCompartments.setHorizontalHeaderItem(4, item)
        self.tableCompartments.verticalHeader().setVisible(False)
        self.tableCompartments.verticalHeader().setSortIndicatorShown(False)
        self.tableCompartments.verticalHeader().setStretchLastSection(False)
        self.compartmentErrorLog = QtGui.QPlainTextEdit(self.splitter_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.compartmentErrorLog.sizePolicy().hasHeightForWidth())
        self.compartmentErrorLog.setSizePolicy(sizePolicy)
        self.compartmentErrorLog.setMaximumSize(QtCore.QSize(16777215, 200))
        self.compartmentErrorLog.setObjectName(_fromUtf8("compartmentErrorLog"))
        self.gridLayout_7.addWidget(self.splitter_4, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageCompartments)
        self.pageSpecies = QtGui.QWidget()
        self.pageSpecies.setObjectName(_fromUtf8("pageSpecies"))
        self.gridLayout = QtGui.QGridLayout(self.pageSpecies)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_8 = QtGui.QLabel(self.pageSpecies)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_8.addWidget(self.label_8, 0, 0, 1, 1)
        self.lineSearchSpecies = QtGui.QLineEdit(self.pageSpecies)
        self.lineSearchSpecies.setObjectName(_fromUtf8("lineSearchSpecies"))
        self.gridLayout_8.addWidget(self.lineSearchSpecies, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.splitter_3 = QtGui.QSplitter(self.pageSpecies)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.tableSpecies = QtGui.QTableWidget(self.splitter_3)
        self.tableSpecies.setAlternatingRowColors(True)
        self.tableSpecies.setCornerButtonEnabled(True)
        self.tableSpecies.setProperty("RowNumber", 1)
        self.tableSpecies.setObjectName(_fromUtf8("tableSpecies"))
        self.tableSpecies.setColumnCount(7)
        self.tableSpecies.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableSpecies.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableSpecies.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableSpecies.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableSpecies.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableSpecies.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableSpecies.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableSpecies.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableSpecies.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableSpecies.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableSpecies.setItem(0, 2, item)
        self.tableSpecies.verticalHeader().setVisible(False)
        self.tableSpecies.verticalHeader().setSortIndicatorShown(False)
        self.tableSpecies.verticalHeader().setStretchLastSection(False)
        self.speciesErrorLog = QtGui.QPlainTextEdit(self.splitter_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speciesErrorLog.sizePolicy().hasHeightForWidth())
        self.speciesErrorLog.setSizePolicy(sizePolicy)
        self.speciesErrorLog.setMaximumSize(QtCore.QSize(16777215, 200))
        self.speciesErrorLog.setReadOnly(True)
        self.speciesErrorLog.setOverwriteMode(True)
        self.speciesErrorLog.setObjectName(_fromUtf8("speciesErrorLog"))
        self.gridLayout.addWidget(self.splitter_3, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageSpecies)
        self.pageParameters = QtGui.QWidget()
        self.pageParameters.setObjectName(_fromUtf8("pageParameters"))
        self.gridLayout_11 = QtGui.QGridLayout(self.pageParameters)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_9 = QtGui.QLabel(self.pageParameters)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_10.addWidget(self.label_9, 0, 0, 1, 1)
        self.lineSearchParameters = QtGui.QLineEdit(self.pageParameters)
        self.lineSearchParameters.setObjectName(_fromUtf8("lineSearchParameters"))
        self.gridLayout_10.addWidget(self.lineSearchParameters, 0, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.splitter_2 = QtGui.QSplitter(self.pageParameters)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.tableParameters = QtGui.QTableWidget(self.splitter_2)
        self.tableParameters.setAlternatingRowColors(True)
        self.tableParameters.setCornerButtonEnabled(True)
        self.tableParameters.setProperty("RowNumber", 1)
        self.tableParameters.setObjectName(_fromUtf8("tableParameters"))
        self.tableParameters.setColumnCount(5)
        self.tableParameters.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableParameters.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableParameters.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableParameters.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableParameters.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableParameters.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableParameters.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableParameters.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableParameters.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableParameters.setItem(0, 2, item)
        self.tableParameters.verticalHeader().setVisible(False)
        self.tableParameters.verticalHeader().setSortIndicatorShown(False)
        self.tableParameters.verticalHeader().setStretchLastSection(False)
        self.parameterErrorLog = QtGui.QPlainTextEdit(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parameterErrorLog.sizePolicy().hasHeightForWidth())
        self.parameterErrorLog.setSizePolicy(sizePolicy)
        self.parameterErrorLog.setMaximumSize(QtCore.QSize(16777215, 200))
        self.parameterErrorLog.setFrameShape(QtGui.QFrame.StyledPanel)
        self.parameterErrorLog.setFrameShadow(QtGui.QFrame.Sunken)
        self.parameterErrorLog.setReadOnly(True)
        self.parameterErrorLog.setOverwriteMode(True)
        self.parameterErrorLog.setObjectName(_fromUtf8("parameterErrorLog"))
        self.gridLayout_11.addWidget(self.splitter_2, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageParameters)
        self.pageReactions = QtGui.QWidget()
        self.pageReactions.setObjectName(_fromUtf8("pageReactions"))
        self.gridLayout_12 = QtGui.QGridLayout(self.pageReactions)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_10 = QtGui.QLabel(self.pageReactions)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_6.addWidget(self.label_10)
        self.lineSearchReactions = QtGui.QLineEdit(self.pageReactions)
        self.lineSearchReactions.setObjectName(_fromUtf8("lineSearchReactions"))
        self.horizontalLayout_6.addWidget(self.lineSearchReactions)
        self.gridLayout_12.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.tableReactions = QtGui.QTableWidget(self.pageReactions)
        self.tableReactions.setObjectName(_fromUtf8("tableReactions"))
        self.tableReactions.setColumnCount(5)
        self.tableReactions.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableReactions.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableReactions.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableReactions.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableReactions.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableReactions.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableReactions.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableReactions.setItem(0, 1, item)
        self.tableReactions.verticalHeader().setVisible(False)
        self.gridLayout_12.addWidget(self.tableReactions, 1, 0, 1, 1)
        self.plainTextEdit_2 = QtGui.QPlainTextEdit(self.pageReactions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_2.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_2.setSizePolicy(sizePolicy)
        self.plainTextEdit_2.setObjectName(_fromUtf8("plainTextEdit_2"))
        self.gridLayout_12.addWidget(self.plainTextEdit_2, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageReactions)
        self.pageMatrices = QtGui.QWidget()
        self.pageMatrices.setObjectName(_fromUtf8("pageMatrices"))
        self.gridLayout_13 = QtGui.QGridLayout(self.pageMatrices)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.tabWidget_2 = QtGui.QTabWidget(self.pageMatrices)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tabStoichMatrix = QtGui.QWidget()
        self.tabStoichMatrix.setObjectName(_fromUtf8("tabStoichMatrix"))
        self.gridLayout_23 = QtGui.QGridLayout(self.tabStoichMatrix)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_23 = QtGui.QLabel(self.tabStoichMatrix)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_7.addWidget(self.label_23)
        self.lineEditStoichMatrix = QtGui.QLineEdit(self.tabStoichMatrix)
        self.lineEditStoichMatrix.setObjectName(_fromUtf8("lineEditStoichMatrix"))
        self.horizontalLayout_7.addWidget(self.lineEditStoichMatrix)
        self.gridLayout_23.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.tableStoichMatrix = QtGui.QTableWidget(self.tabStoichMatrix)
        self.tableStoichMatrix.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableStoichMatrix.setObjectName(_fromUtf8("tableStoichMatrix"))
        self.tableStoichMatrix.setColumnCount(0)
        self.tableStoichMatrix.setRowCount(0)
        self.gridLayout_23.addWidget(self.tableStoichMatrix, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.tabStoichMatrix, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_22 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.label_11 = QtGui.QLabel(self.tab_4)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_22.addWidget(self.label_11, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.gridLayout_13.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageMatrices)
        self.pageCode = QtGui.QWidget()
        self.pageCode.setObjectName(_fromUtf8("pageCode"))
        self.gridLayout_14 = QtGui.QGridLayout(self.pageCode)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.label_12 = QtGui.QLabel(self.pageCode)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_14.addWidget(self.label_12, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageCode)
        self.pageSimulation = QtGui.QWidget()
        self.pageSimulation.setObjectName(_fromUtf8("pageSimulation"))
        self.gridLayout_19 = QtGui.QGridLayout(self.pageSimulation)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.label_20 = QtGui.QLabel(self.pageSimulation)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_19.addWidget(self.label_20, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageSimulation)
        self.pageTimeCourse = QtGui.QWidget()
        self.pageTimeCourse.setObjectName(_fromUtf8("pageTimeCourse"))
        self.gridLayout_18 = QtGui.QGridLayout(self.pageTimeCourse)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.label_13 = QtGui.QLabel(self.pageTimeCourse)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_18.addWidget(self.label_13, 0, 0, 1, 1)
        self.gridLayout_16 = QtGui.QGridLayout()
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.label_14 = QtGui.QLabel(self.pageTimeCourse)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_16.addWidget(self.label_14, 0, 0, 1, 1)
        self.lineIntervalSize = QtGui.QLineEdit(self.pageTimeCourse)
        self.lineIntervalSize.setObjectName(_fromUtf8("lineIntervalSize"))
        self.gridLayout_16.addWidget(self.lineIntervalSize, 1, 1, 1, 1)
        self.lineDuration = QtGui.QLineEdit(self.pageTimeCourse)
        self.lineDuration.setObjectName(_fromUtf8("lineDuration"))
        self.gridLayout_16.addWidget(self.lineDuration, 0, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.pageTimeCourse)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_16.addWidget(self.label_16, 1, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.pageTimeCourse)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_16.addWidget(self.label_17, 1, 2, 1, 1)
        self.lineIntervals = QtGui.QLineEdit(self.pageTimeCourse)
        self.lineIntervals.setObjectName(_fromUtf8("lineIntervals"))
        self.gridLayout_16.addWidget(self.lineIntervals, 1, 3, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_16, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.line = QtGui.QFrame(self.pageTimeCourse)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_4.addWidget(self.line)
        self.gridLayout_18.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_18 = QtGui.QLabel(self.pageTimeCourse)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout.addWidget(self.label_18)
        self.lineEdit_7 = QtGui.QLineEdit(self.pageTimeCourse)
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.horizontalLayout.addWidget(self.lineEdit_7)
        self.gridLayout_18.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.line_2 = QtGui.QFrame(self.pageTimeCourse)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_5.addWidget(self.line_2)
        self.gridLayout_18.addLayout(self.horizontalLayout_5, 4, 0, 1, 1)
        self.gridLayout_17 = QtGui.QGridLayout()
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.spinBox = QtGui.QSpinBox(self.pageTimeCourse)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout_17.addWidget(self.spinBox, 0, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.pageTimeCourse)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_17.addWidget(self.label_19, 0, 0, 1, 1)
        self.tableWidget = QtGui.QTableWidget(self.pageTimeCourse)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_17.addWidget(self.tableWidget, 1, 1, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_17, 5, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButtonRun = QtGui.QPushButton(self.pageTimeCourse)
        self.pushButtonRun.setObjectName(_fromUtf8("pushButtonRun"))
        self.horizontalLayout_3.addWidget(self.pushButtonRun)
        self.pushButtonRevert = QtGui.QPushButton(self.pageTimeCourse)
        self.pushButtonRevert.setObjectName(_fromUtf8("pushButtonRevert"))
        self.horizontalLayout_3.addWidget(self.pushButtonRevert)
        self.progressBarTimeCourse = QtGui.QProgressBar(self.pageTimeCourse)
        self.progressBarTimeCourse.setProperty("value", 24)
        self.progressBarTimeCourse.setObjectName(_fromUtf8("progressBarTimeCourse"))
        self.horizontalLayout_3.addWidget(self.progressBarTimeCourse)
        self.gridLayout_18.addLayout(self.horizontalLayout_3, 6, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageTimeCourse)
        self.pageLSA = QtGui.QWidget()
        self.pageLSA.setObjectName(_fromUtf8("pageLSA"))
        self.gridLayout_20 = QtGui.QGridLayout(self.pageLSA)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.label_21 = QtGui.QLabel(self.pageLSA)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_20.addWidget(self.label_21, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageLSA)
        self.pageGSA = QtGui.QWidget()
        self.pageGSA.setObjectName(_fromUtf8("pageGSA"))
        self.gridLayout_21 = QtGui.QGridLayout(self.pageGSA)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.label_22 = QtGui.QLabel(self.pageGSA)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_21.addWidget(self.label_22, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageGSA)
        self.gridLayout_9.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 715, 24))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_as = QtGui.QAction(MainWindow)
        self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))
        self.actionUndo = QtGui.QAction(MainWindow)
        self.actionUndo.setObjectName(_fromUtf8("actionUndo"))
        self.actionRedo = QtGui.QAction(MainWindow)
        self.actionRedo.setObjectName(_fromUtf8("actionRedo"))
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "SBML-Analaysis-Toolbox", None))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Toolbox", None))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "Model", None))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "Compartments", None))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "Species", None))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "Parameters", None))
        self.treeWidget.topLevelItem(0).child(3).setText(0, _translate("MainWindow", "Reactions", None))
        self.treeWidget.topLevelItem(0).child(4).setText(0, _translate("MainWindow", "Matrices", None))
        self.treeWidget.topLevelItem(0).child(5).setText(0, _translate("MainWindow", "Code", None))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "Simulation", None))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "Time Course", None))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "Local Sensitivity Analysis", None))
        self.treeWidget.topLevelItem(1).child(2).setText(0, _translate("MainWindow", "Global Sensitivity Analysis", None))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "Model", None))
        self.lineEditModelName.setText(_translate("MainWindow", "New Model", None))
        self.label_2.setText(_translate("MainWindow", "Time Units", None))
        self.lineEditTimeUnits.setText(_translate("MainWindow", "s", None))
        self.label_3.setText(_translate("MainWindow", "Volume Unit", None))
        self.lineEditVolumeUnits.setText(_translate("MainWindow", "ml", None))
        self.label_4.setText(_translate("MainWindow", "Quantity Unit", None))
        self.lineEditQuantityUnits.setText(_translate("MainWindow", "mmol", None))
        self.label_5.setText(_translate("MainWindow", "Initial Time", None))
        self.lineEdit_5.setText(_translate("MainWindow", "0", None))
        self.label_6.setText(_translate("MainWindow", "Current Time", None))
        self.lineEdit_6.setText(_translate("MainWindow", "0", None))
        self.label_24.setText(_translate("MainWindow", "Error Log", None))
        self.pushButtonModelCommit.setText(_translate("MainWindow", "Commit", None))
        self.pushButtonModelRevert.setText(_translate("MainWindow", "Revert", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Details", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Annotation", None))
        self.label_7.setText(_translate("MainWindow", "Search:", None))
        self.tableCompartments.setSortingEnabled(True)
        item = self.tableCompartments.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "#", None))
        item = self.tableCompartments.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.tableCompartments.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Initial Volume", None))
        item = self.tableCompartments.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Volume", None))
        item = self.tableCompartments.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "MetaID", None))
        self.label_8.setText(_translate("MainWindow", "Search:", None))
        self.tableSpecies.setSortingEnabled(True)
        item = self.tableSpecies.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "#", None))
        item = self.tableSpecies.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.tableSpecies.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Initial Cc", None))
        item = self.tableSpecies.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Cc", None))
        item = self.tableSpecies.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Compartment", None))
        item = self.tableSpecies.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Boundary?", None))
        item = self.tableSpecies.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "MetaId", None))
        __sortingEnabled = self.tableSpecies.isSortingEnabled()
        self.tableSpecies.setSortingEnabled(False)
        item = self.tableSpecies.item(0, 1)
        item.setText(_translate("MainWindow", "New Species", None))
        item = self.tableSpecies.item(0, 2)
        item.setText(_translate("MainWindow", "1", None))
        self.tableSpecies.setSortingEnabled(__sortingEnabled)
        self.speciesErrorLog.setDocumentTitle(_translate("MainWindow", "Species Error Log", None))
        self.label_9.setText(_translate("MainWindow", "Search:", None))
        self.tableParameters.setSortingEnabled(True)
        item = self.tableParameters.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Index", None))
        item = self.tableParameters.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.tableParameters.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Value", None))
        item = self.tableParameters.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Variable", None))
        item = self.tableParameters.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "MetaId", None))
        __sortingEnabled = self.tableParameters.isSortingEnabled()
        self.tableParameters.setSortingEnabled(False)
        item = self.tableParameters.item(0, 1)
        item.setText(_translate("MainWindow", "New Parameter", None))
        item = self.tableParameters.item(0, 2)
        item.setText(_translate("MainWindow", "1", None))
        self.tableParameters.setSortingEnabled(__sortingEnabled)
        self.parameterErrorLog.setDocumentTitle(_translate("MainWindow", "Parameter Error Log", None))
        self.label_10.setText(_translate("MainWindow", "Search:", None))
        item = self.tableReactions.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.tableReactions.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Index", None))
        item = self.tableReactions.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.tableReactions.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Equation", None))
        item = self.tableReactions.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Modifiers", None))
        item = self.tableReactions.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Compartment", None))
        __sortingEnabled = self.tableReactions.isSortingEnabled()
        self.tableReactions.setSortingEnabled(False)
        item = self.tableReactions.item(0, 1)
        item.setText(_translate("MainWindow", "New Reaction", None))
        self.tableReactions.setSortingEnabled(__sortingEnabled)
        self.label_23.setText(_translate("MainWindow", "Search:", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabStoichMatrix), _translate("MainWindow", "Stoichiometry Matrix", None))
        self.label_11.setText(_translate("MainWindow", "To be added...", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "To be added...", None))
        self.label_12.setText(_translate("MainWindow", "Layout Page to be Added", None))
        self.label_20.setText(_translate("MainWindow", "To be Added", None))
        self.label_13.setText(_translate("MainWindow", "Time Course", None))
        self.label_14.setText(_translate("MainWindow", "Duration", None))
        self.lineIntervalSize.setText(_translate("MainWindow", "0.1", None))
        self.lineDuration.setText(_translate("MainWindow", "1", None))
        self.label_16.setText(_translate("MainWindow", "Interval Size", None))
        self.label_17.setText(_translate("MainWindow", "Intervals", None))
        self.lineIntervals.setText(_translate("MainWindow", "10", None))
        self.label_18.setText(_translate("MainWindow", "Integration Interval", None))
        self.lineEdit_7.setText(_translate("MainWindow", "0 to 1", None))
        self.label_19.setText(_translate("MainWindow", "TextLabel", None))
        self.pushButtonRun.setText(_translate("MainWindow", "Run", None))
        self.pushButtonRevert.setText(_translate("MainWindow", "Revert", None))
        self.label_21.setText(_translate("MainWindow", "To be added", None))
        self.label_22.setText(_translate("MainWindow", "To be added", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionSave_as.setText(_translate("MainWindow", "Save as...", None))
        self.actionSave_as.setShortcut(_translate("MainWindow", "Ctrl+Shift+S", None))
        self.actionUndo.setText(_translate("MainWindow", "Undo", None))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z", None))
        self.actionRedo.setText(_translate("MainWindow", "Redo", None))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Shift+Z, Ctrl+Y", None))
        self.actionNew.setText(_translate("MainWindow", "New", None))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N", None))

